name: Build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        run: corepack enable && pnpm -v

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter package-name build